### register a user
POST http://localhost:3001/user
Content-Type: application/json

{
    "email": "abc@yahoo.com",
    "password": "kamigamiX0!"
}

### delete a user
DELETE http://localhost:3001/user
Content-Type: application/json

{
    "email": "abc@yahoo.com"
}

### create a merchant
POST http://localhost:3001/merchant
Content-Type: application/json

{
    "name": "London Hydro"
}

### create a customer
POST http://localhost:3001/customer
Content-Type: application/json

{
    "email": "almuali699@gmail.com",
    "fname": "Ali",
    "lname": "Al-Musawi"
}

### create an account
POST http://localhost:3001/account
Content-Type: application/json

{
    "email": "almuali699@gmail.com",
    "number": "1111222233334444"
}